<?php

namespace Database\Seeders;

use App\Models\Equipment;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EquipmentSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the equipment table with sample data.
     */
    public function run(): void
    {
        $equipment = [
            [
                'equipment_code' => 'EQ-001',
                'name' => 'Digital Multimeter',
                'category' => 'Electrical Testing',
                'manufacturer' => 'Fluke',
                'model' => '87-V',
                'serial_number' => 'FL-2024-001',
                'asset_number' => 'AST-0001',
                'purchase_date' => '2023-01-15',
                'purchase_cost' => 450.00,
                'location' => 'Lab Room A',
                'responsible_person' => 2,
                'status' => 'available',
                'specifications' => ['voltage_range' => '600V', 'resolution' => '0.1mV', 'battery' => '9V'],
                'calibration_required' => true,
                'last_maintenance' => '2024-06-10',
                'next_maintenance' => '2025-06-10',
                'notes' => 'Recently calibrated, working properly',
            ],
            [
                'equipment_code' => 'EQ-002',
                'name' => 'Oscilloscope',
                'category' => 'Electronic Measurement',
                'manufacturer' => 'Tektronix',
                'model' => 'TDS 2024B',
                'serial_number' => 'TEK-2024-002',
                'asset_number' => 'AST-0002',
                'purchase_date' => '2022-11-20',
                'purchase_cost' => 1200.00,
                'location' => 'Lab Room B',
                'responsible_person' => 2,
                'status' => 'in_use',
                'specifications' => ['bandwidth' => '200MHz', 'channels' => 4, 'sample_rate' => '1GS/s'],
                'calibration_required' => true,
                'last_maintenance' => '2024-01-15',
                'next_maintenance' => '2025-01-15',
                'notes' => 'Calibration due this month',
            ],
            [
                'equipment_code' => 'EQ-003',
                'name' => 'Pressure Gauge (0-100 PSI)',
                'category' => 'Pressure Testing',
                'manufacturer' => 'Wika',
                'model' => '232.53',
                'serial_number' => 'WIK-2024-003',
                'asset_number' => 'AST-0003',
                'purchase_date' => '2023-05-22',
                'purchase_cost' => 250.00,
                'location' => 'Lab Room C',
                'responsible_person' => 3,
                'status' => 'available',
                'specifications' => ['range' => '0-100 PSI', 'accuracy' => '±0.5%', 'connection' => '1/4" NPT'],
                'calibration_required' => true,
                'last_maintenance' => '2024-08-05',
                'next_maintenance' => '2025-08-05',
                'notes' => 'Properly maintained and calibrated',
            ],
            [
                'equipment_code' => 'EQ-004',
                'name' => 'Temperature Logger',
                'category' => 'Temperature Control',
                'manufacturer' => 'Omega',
                'model' => 'OMB-DAQ-3007',
                'serial_number' => 'OMG-2024-004',
                'asset_number' => 'AST-0004',
                'purchase_date' => '2024-02-10',
                'purchase_cost' => 600.00,
                'location' => 'Storage Area',
                'responsible_person' => 3,
                'status' => 'maintenance',
                'specifications' => ['channels' => 8, 'accuracy' => '±0.5°C', 'range' => '-20 to 60°C'],
                'calibration_required' => true,
                'last_maintenance' => '2023-09-20',
                'next_maintenance' => '2024-09-20',
                'notes' => 'Calibration overdue - schedule maintenance ASAP',
            ],
            [
                'equipment_code' => 'EQ-005',
                'name' => 'Function Generator',
                'category' => 'Signal Generation',
                'manufacturer' => 'Agilent',
                'model' => '33220A',
                'serial_number' => 'AGI-2024-005',
                'asset_number' => 'AST-0005',
                'purchase_date' => '2023-08-18',
                'purchase_cost' => 800.00,
                'location' => 'Lab Room A',
                'responsible_person' => 2,
                'status' => 'available',
                'specifications' => ['frequency_range' => '0.1Hz to 25MHz', 'output' => '0 to 10V', 'waveforms' => 'Sine, Square, Triangle'],
                'calibration_required' => true,
                'last_maintenance' => '2024-07-22',
                'next_maintenance' => '2025-07-22',
                'notes' => 'Fully operational and calibrated',
            ],
            [
                'equipment_code' => 'EQ-006',
                'name' => 'Power Analyzer',
                'category' => 'Electrical Testing',
                'manufacturer' => 'Hioki',
                'model' => 'PW3337-03',
                'serial_number' => 'HIK-2024-006',
                'asset_number' => 'AST-0006',
                'purchase_date' => '2023-03-05',
                'purchase_cost' => 950.00,
                'location' => 'Lab Room B',
                'responsible_person' => 4,
                'status' => 'in_use',
                'specifications' => ['channels' => 4, 'voltage_range' => '10V-600V', 'power_measurement' => 'True RMS'],
                'calibration_required' => true,
                'last_maintenance' => '2024-02-14',
                'next_maintenance' => '2025-02-14',
                'notes' => 'Approaching calibration date',
            ],
            [
                'equipment_code' => 'EQ-007',
                'name' => 'Thermal Camera',
                'category' => 'Thermal Imaging',
                'manufacturer' => 'FLIR',
                'model' => 'E-Series',
                'serial_number' => 'FLR-2024-007',
                'asset_number' => 'AST-0007',
                'purchase_date' => '2024-01-08',
                'purchase_cost' => 2500.00,
                'location' => 'Equipment Storage',
                'responsible_person' => 4,
                'status' => 'available',
                'specifications' => ['resolution' => '320x256', 'thermal_sensitivity' => '<50mK', 'temperature_range' => '-20 to 250°C'],
                'calibration_required' => true,
                'last_maintenance' => '2024-09-12',
                'next_maintenance' => '2025-09-12',
                'notes' => 'Recently acquired, fully functional',
            ],
            [
                'equipment_code' => 'EQ-008',
                'name' => 'Calibration Oven',
                'category' => 'Temperature Control',
                'manufacturer' => 'Fluke',
                'model' => '9147',
                'serial_number' => 'FLU-2024-008',
                'asset_number' => 'AST-0008',
                'purchase_date' => '2022-06-12',
                'purchase_cost' => 3200.00,
                'location' => 'Lab Room C',
                'responsible_person' => 3,
                'status' => 'retired',
                'specifications' => ['temperature_range' => '0 to 650°C', 'accuracy' => '±2°C', 'capacity' => '45 liters'],
                'calibration_required' => true,
                'last_maintenance' => '2023-12-01',
                'next_maintenance' => '2024-12-01',
                'notes' => 'Currently not in use - undergoing refurbishment',
            ],
        ];

        foreach ($equipment as $item) {
            Equipment::create($item);
        }
    }
}
