@extends('layouts.dashboard')

@section('title', 'Certificate Preview')
@section('page-title', 'Certificate Preview')
@section('page-subtitle', $certificate->certificate_number)

@section('sidebar-nav')
    @include('signatory.partials.sidebar')
@endsection

@section('content')
    <div class="max-w-4xl mx-auto space-y-4 sm:space-y-6">
        <!-- Header -->
        <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
            <div>
                <h2 class="text-xl sm:text-2xl font-bold text-gray-900 dark:text-white break-words">
                    {{ $certificate->certificate_number }}
                </h2>
                <p class="text-sm text-gray-600 dark:text-gray-400 mt-1 break-words">
                    Status: 
                    @if($certificate->signed_by)
                        <span class="text-emerald-600 font-medium">Signed & Ready for Release</span>
                    @else
                        <span class="text-amber-600 font-medium">Pending Approval</span>
                    @endif
                </p>
                <p class="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    Generated by: {{ $certificate->issuedBy?->name ?? 'System' }}
                </p>
            </div>
            <div class="flex flex-col sm:flex-row gap-2 w-full sm:w-auto">
                @if($certificate->signed_by)
                    <button class="w-full sm:w-auto px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium rounded-lg transition-colors">
                        📥 Download PDF
                    </button>
                @else
                    <button disabled class="w-full sm:w-auto px-4 py-2 bg-gray-300 dark:bg-gray-700 text-gray-500 dark:text-gray-500 text-sm font-medium rounded-lg cursor-not-allowed" title="Certificate must be signed before download">
                        🔒 Download Locked
                    </button>
                @endif
                <a href="{{ route('signatory.certificates') }}" class="w-full sm:w-auto px-4 py-2 bg-gray-200 dark:bg-gray-600 text-gray-800 dark:text-gray-200 rounded-lg text-sm font-medium text-center transition-colors">
                    Back
                </a>
            </div>
        </div>

        <!-- Certificate Document (Print Preview) -->
        <div class="bg-white dark:bg-gray-800 rounded-[20px] shadow-md border border-gray-200 dark:border-gray-700 p-4 sm:p-8 lg:p-12 overflow-hidden" style="background: white;">
            <!-- Certificate Header -->
            <div class="text-center pb-6 sm:pb-8 border-b-2 border-gray-300">
                <h1 class="text-2xl sm:text-3xl font-bold text-gray-900 mb-2 break-words">CERTIFICATE OF CALIBRATION</h1>
                <p class="text-sm text-gray-600">{{ $certificate->certificate_number }}</p>
            </div>

            <!-- Certificate Body -->
            <div class="mt-6 sm:mt-8 space-y-6 text-gray-900 text-sm">
                <!-- Calibration Info -->
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-8">
                    <div>
                        <p class="font-semibold text-gray-600 mb-1">CALIBRATION PERFORMED FOR:</p>
                        <p class="font-bold break-words">{{ $certificate->jobOrder?->customer?->name ?? 'N/A' }}</p>
                        <p class="text-xs text-gray-600 mt-2">{{ $certificate->jobOrder?->job_order_number ?? 'N/A' }}</p>
                    </div>
                    <div>
                        <p class="font-semibold text-gray-600 mb-1">CALIBRATION DATE:</p>
                        <p class="font-bold break-words">{{ $certificate->calibration?->calibration_date?->setTimezone('Asia/Manila')->format('F d, Y') ?? 'N/A' }}</p>
                        <p class="text-xs text-gray-600 mt-2">Certificate Date: {{ $certificate->signed_at?->setTimezone('Asia/Manila')->format('F d, Y') ?? 'N/A' }}</p>
                    </div>
                </div>

                <!-- Technician & Reference -->
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-8">
                    <div>
                        <p class="font-semibold text-gray-600 mb-1">CALIBRATED BY:</p>
                        <p class="font-bold break-words">{{ $certificate->calibration?->performedBy?->name ?? 'N/A' }}</p>
                    </div>
                    <div>
                        <p class="font-semibold text-gray-600 mb-1">PROCEDURE REFERENCE:</p>
                        <p class="font-bold break-words">{{ $certificate->calibration?->procedure_reference ?? 'Not Specified' }}</p>
                    </div>
                </div>

                <!-- Measurement Summary -->
                <div class="mt-8">
                    <p class="font-semibold text-gray-600 mb-3">MEASUREMENT RESULTS:</p>
                    <div class="overflow-x-auto">
                    <table class="w-full min-w-[720px] text-xs border-collapse">
                        <thead>
                            <tr class="border-b-2 border-gray-400">
                                <th class="text-left py-2 px-2 font-bold">Point</th>
                                <th class="text-left py-2 px-2 font-bold">Reference</th>
                                <th class="text-left py-2 px-2 font-bold">UUT Reading</th>
                                <th class="text-left py-2 px-2 font-bold">Error</th>
                                <th class="text-left py-2 px-2 font-bold">Uncertainty</th>
                                <th class="text-left py-2 px-2 font-bold">Result</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($certificate->calibration?->measurementPoints ?? [] as $point)
                                <tr class="border-b border-gray-200">
                                    <td class="py-2 px-2">{{ $point->point_number }}</td>
                                    <td class="py-2 px-2">{{ number_format($point->reference_value, 4) }}</td>
                                    <td class="py-2 px-2">{{ number_format($point->uut_reading, 4) }}</td>
                                    <td class="py-2 px-2">{{ number_format($point->error, 4) }}</td>
                                    <td class="py-2 px-2">{{ $point->uncertainty ? number_format($point->uncertainty, 4) : 'N/A' }}</td>
                                    <td class="py-2 px-2 font-bold">{{ strtoupper($point->status) }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    </div>
                </div>

                <!-- Overall Result -->
                <div class="mt-8 p-4 bg-gray-50 rounded border border-gray-300">
                    <p class="font-semibold text-gray-600 mb-2">OVERALL RESULT:</p>
                    @if($certificate->calibration?->pass_fail === 'pass')
                        <p class="text-lg font-bold text-emerald-700">✓ PASS - Equipment meets specifications</p>
                    @elseif($certificate->calibration?->pass_fail === 'fail')
                        <p class="text-lg font-bold text-rose-700">✗ FAIL - Equipment does not meet specifications</p>
                    @else
                        <p class="text-lg font-bold text-amber-700">~ CONDITIONAL - Equipment meets specifications with limitations</p>
                    @endif
                </div>

                <!-- Signature Section -->
                <div class="mt-10 sm:mt-12 pt-8 border-t-2 border-gray-300 grid grid-cols-1 sm:grid-cols-2 gap-8 sm:gap-12">
                    <div>
                        <p class="font-semibold text-gray-600 mb-8">Technician</p>
                        <div class="border-b-2 border-gray-400" style="height: 40px;"></div>
                        <p class="text-xs text-gray-600 mt-2">{{ $certificate->calibration?->performedBy?->name ?? 'N/A' }}</p>
                        <p class="text-xs text-gray-600">{{ $certificate->calibration?->calibration_date?->setTimezone('Asia/Manila')->format('F d, Y') ?? 'N/A' }}</p>
                    </div>
                    <div>
                        <p class="font-semibold text-gray-600 mb-8">Signatory</p>
                        <div class="border-b-2 border-gray-400" style="height: 40px;"></div>
                        <p class="text-xs text-gray-600 mt-2">{{ $certificate->signedBy?->name ?? 'Not Signed' }}</p>
                        <p class="text-xs text-gray-600">Digital Signature - {{ $certificate->signed_at?->setTimezone('Asia/Manila')->format('F d, Y') ?? 'Pending' }}</p>
                    </div>
                </div>

                <!-- Footer -->
                <div class="mt-12 pt-6 border-t border-gray-300 text-center text-xs text-gray-600">
                    <p>This certificate is valid and ready for customer delivery.</p>
                    <p class="mt-2">Certificate Number: {{ $certificate->certificate_number }}</p>
                </div>
            </div>
        </div>

        <!-- Certificate Info -->
        <div class="bg-white dark:bg-gray-800 rounded-[20px] shadow-md border border-gray-200 dark:border-gray-700 p-4 sm:p-6">
            <h3 class="text-base font-bold text-slate-900 dark:text-white mb-4">ℹ️ Certificate Information</h3>
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-5 gap-4 text-sm">
                <div>
                    <p class="text-xs text-gray-500 dark:text-gray-400 mb-1">Certificate Number</p>
                    <p class="font-semibold text-gray-900 dark:text-white break-words">{{ $certificate->certificate_number }}</p>
                </div>
                <div>
                    <p class="text-xs text-gray-500 dark:text-gray-400 mb-1">Generated By</p>
                    <p class="font-semibold text-gray-900 dark:text-white break-words">{{ $certificate->issuedBy?->name ?? 'System' }}</p>
                </div>
                <div>
                    <p class="text-xs text-gray-500 dark:text-gray-400 mb-1">Signed By</p>
                    <p class="font-semibold text-gray-900 dark:text-white break-words">{{ $certificate->signedBy?->name ?? 'Not Signed' }}</p>
                </div>
                <div>
                    <p class="text-xs text-gray-500 dark:text-gray-400 mb-1">Signed Date</p>
                    <p class="font-semibold text-gray-900 dark:text-white break-words">{{ $certificate->signed_at?->setTimezone('Asia/Manila')->format('M d, Y h:i A') ?? 'Pending' }}</p>
                </div>
                <div>
                    <p class="text-xs text-gray-500 dark:text-gray-400 mb-1">Status</p>
                    @if($certificate->signed_by)
                        <span class="inline-block px-2 py-1 text-xs font-medium rounded-full bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-200">
                            ✓ Approved
                        </span>
                    @else
                        <span class="inline-block px-2 py-1 text-xs font-medium rounded-full bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-200">
                            ⏳ Pending Approval
                        </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection
